### ISSUE TITLE
Polygon strokes

### ISSUE THREAD

**Issue by mbarrenechea** [vasturiano/globe.gl#1]
Do you think it would be possible to add the ability to use strokes in the polygons? It would be very nice to have this because when you have a lot of adjacent polygons is very difficult to differentiate them.

**Comment by vasturiano** [comment]
@mbarrenechea thanks fro reaching out. I think it would be very useful indeed to have such a feature. I see you've initiated a PR at https://github.com/vasturiano/three-globe/pull/1. Let's continue the conversation there. 👍
