### ISSUE TITLE
require() of ES Module /node_modules/three/examples/jsm/renderers/CSS2DRenderer.js from /workspace/storie/spacex/node_modules/globe.gl/dist/globe.gl.common.js not supported. Instead change the require of CSS2DRenderer.js in /node_modules/globe.gl/dist/globe.gl.common.js to a dynamic import() which is available in all CommonJS modules

### ISSUE THREAD

**Issue by chientrm** [vasturiano/globe.gl#105]
**Describe the bug**
```
require() of ES Module /node_modules/three/examples/jsm/renderers/CSS2DRenderer.js from /workspace/storie/spacex/node_modules/globe.gl/dist/globe.gl.common.js not supported. Instead change the require of CSS2DRenderer.js in /node_modules/globe.gl/dist/globe.gl.common.js to a dynamic import() which is available in all CommonJS modules
```

**To Reproduce**
1. `npm init`
2. Add `'type': 'module'` to `package.json`
3. `npm run build` using vite

**Expected behavior**
Build distribution

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, Safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by comicsaint** [comment]
Hello, we resolved the issue using a dynamic import in Next Js
const ReactGlobe = dynamic(import('react-globe.gl'), { ssr: false })

**Comment by chientrm** [comment]
> Hello, we resolved the issue using a dynamic import in Next Js const ReactGlobe = dynamic(import('react-globe.gl'), { ssr: false })

I resolved this by dynamic import in svelte, too. 👍

**Comment by stefanreifenberg** [comment]
hey @chientrm I would love to see how you implemented globe.gl in svelte. Cheers

**Comment by chientrm** [comment]
> hey @chientrm I would love to see how you implemented globe.gl in svelte. Cheers

I no longer use `globe.gl`. Please check my `three-js` globe I implemented myself 👍
