### ISSUE TITLE
Trying to render Arcs with NextJS

### ISSUE THREAD

**Issue by comicsaint** [vasturiano/globe.gl#106]
**Describe the bug**
Using next/dynamic import to import react-globe.gl

**To Reproduce**
Load Arcs with following useEffect code:
const [arcsData, setArcsData] = useState([]) 
  //const [generatedData, setGeneratedData] = useState([]); 

  useEffect(()=>{
    const N = 20
      const gData = [...Array(N).keys()].map(() => ({
        startLat: (Math.random() - 0.5) * 180,
        startLng: (Math.random() - 0.5) * 360,
        endLat: (Math.random() - 0.5) * 180,
        endLng: (Math.random() - 0.5) * 360,
        color: [['red', 'white', 'blue', 'green'][Math.round(Math.random() * 3)], ['red', 'white', 'blue', 'green'][Math.round(Math.random() * 3)]]
      }))

      //setGeneratedData(gData);
      setArcsData(gData)
  },[])

**Expected behavior**
Like to see the arcs animating on the globe

**Screenshots**
<img width="892" alt="Screenshot 2022-05-02 at 13 44 37" src="https://user-images.githubusercontent.com/75342710/166228749-50ac6ffe-e1e9-43ab-88df-1ec90ed31703.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser: Firefow 99.01, Brave 1.38

**Additional context**
Would be good to find out how to debug issues like this as well

**Comment by vasturiano** [comment]
@comicsaint can you make a reproducible example on https://codesandbox.io/ that shows your issue?

**Comment by comicsaint** [comment]
Let see if this works. I couldn't get that dynamic import to run properly in the sandbox
https://codesandbox.io/s/adoring-violet-bbuozj

**Comment by vasturiano** [comment]
@comicsaint glad to hear. It's probably something related to your app setup then. Closing the issue for now.
