### ISSUE TITLE
How to make globe specific lat&lng to face to camera?

### ISSUE THREAD

**Issue by KevinZhang19870314** [vasturiano/globe.gl#115]
Hi, is there anyway I can rotate globe to specific angle, then to make specific lat&lng to face to camera? I know we can use `Globe.rotateX, Globe.rotateY` to spefici angel, but given lat&lng, how to calculate the angel? Also the globe is `autoRotate` set to true.

**Comment by vasturiano** [comment]
@KevinZhang19870314 please see `pointOfView({ lat, lng, altitude }, [ms])` on the [Render controls](https://github.com/vasturiano/globe.gl#render-control).

**Comment by KevinZhang19870314** [comment]
Thank you @vasturiano ! That works.
