### ISSUE TITLE
How i can disable the glow around the globe?

### ISSUE THREAD

**Issue by aguiar-us** [vasturiano/globe.gl#132]
How can I disable or simply decrease the strength of the glow around the globe?

![image](https://user-images.githubusercontent.com/80774764/200137807-1b214caa-162c-4340-a8a4-a759745d8aeb.png)

**Comment by vasturiano** [comment]
```js
.showAtmosphere(false)
```

https://github.com/vasturiano/globe.gl#globe-layer
