### ISSUE TITLE
Submarine cables data

### ISSUE THREAD

**Issue by mrienstra** [vasturiano/globe.gl#136]
The "submarine cables" example is broken:
https://github.com/vasturiano/globe.gl/blob/671a650/example/submarine-cables/index.html
https://vasturiano.github.io/globe.gl/example/submarine-cables/index.html

This is failing:
https://raw.githubusercontent.com/telegeography/www.submarinecablemap.com/master/web/public/api/v3/cable/cable-geo.json

Because this repository is now private or deleted:
https://github.com/telegeography/www.submarinecablemap.com
([Most recent Internet Archive copy](https://web.archive.org/web/20221110120103/https://github.com/telegeography/www.submarinecablemap.com))

The Internet Archive has the data:
https://web.archive.org/web/20220000000000*/https://raw.githubusercontent.com/telegeography/www.submarinecablemap.com/master/web/public/api/v3/cable/cable-geo.json

And it can also be found here:
https://www.submarinecablemap.com/api/v3/cable/cable-geo.json

That's also on the Internet Archive:
https://web.archive.org/web/20220000000000*/https://www.submarinecablemap.com/api/v3/cable/cable-geo.json

... But I'm not sure if it's permissible to use the data anymore, it's not clear the API is intended to be public. Presumably using a copy of the old data (while it was still on GitHub) would be OK?

Selecting "About" on https://www.submarinecablemap.com/ shows:
>Any reference to TeleGeography’s Submarine Cable Map, URL, or any screencapture of the map is made available under the [Creative Commons License: Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/). Contact [info@telegeography.com](mailto:info@telegeography.com) to complete the relevant content release documentation.

Looking at the old GitHub repo, this text only talks about the map:
>Our map is made available under the following [Creative Commons License: Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)](https://web.archive.org/web/20221110120103/https://creativecommons.org/licenses/by-nc-sa/3.0/).

... But it also gives instructions on downloading the data, and the [LICENSE](https://web.archive.org/web/20220816215911/https://github.com/telegeography/www.submarinecablemap.com/blob/master/LICENSE) file seems to apply the Creative Commons license to the entire repo, which includes the data.

Seems like the easy & safe fix would be to place a copy of the data (from before the repo was made inaccessible) into this repo. If you'd prefer to keep the data external, or use the latest data, maybe reach out to [info@telegeography.com](mailto:info@telegeography.com) to see if it's OK to use https://www.submarinecablemap.com/api/v3/cable/cable-geo.json

**Comment by phocks** [comment]
Submarine cables example seems to be broken again :(
