### ISSUE TITLE
How to add animation to the globe

### ISSUE THREAD

**Issue by advaith-unnikrishnan** [vasturiano/globe.gl#143]
Hi @vasturiano 
Thanks for building this amazing tool. I was using the globe.gl in one of my projects and wanted to add a spin animation to the globe and  I encountered an issue.
- I tried to animate the rendered div containing the globe using CSS, but I am unable to select only the globe.
- Is there any way to select only the globe and add specific animation to it?

If you could share any helpful resources it would be great 🙂

**Comment by vasturiano** [comment]
@advaith-unnikrishnan thanks for reaching out.

You can tell the controls to continuously animate the spin. Like it's done in [this example](https://globe.gl/example/world-population/).

https://github.com/vasturiano/globe.gl/blob/e35b68b66362e5199cf3371a9154f9074c39244a/example/world-population/index.html#L35-L37

**Comment by advaith-unnikrishnan** [comment]
Thanks for the help. It works now.

I have one more question, is it possible to adjust the scale of the globe? In the documentation, I found only the parameters to adjust the height and width of the canvas. If you could help with this it would be great.

**Comment by vasturiano** [comment]
Scale as in zoom level? If so, you can adjust that using [pointOfView](https://github.com/vasturiano/globe.gl#render-control).

**Comment by advaith-unnikrishnan** [comment]
Thanks for the help 🙂
