### ISSUE TITLE
Using HTML Element Layer Removes All Arcs

### ISSUE THREAD

**Issue by dunlavy** [vasturiano/globe.gl#148]
``` typescript
Globe({ animateIn: false, waitForGlobeReady: true })
	.width(width)
	.backgroundColor("#FFFFFF00")
	.globeImageUrl("/assets/earth.jpg")
	.showAtmosphere(false)
	.onPolygonClick((polygon, ev, { lat, lng }) => polyClickHandler(polygon, lat, lng))
	.arcsData(<any>advisorFeatures)
	.arcColor("color")
	.arcDashAnimateTime(3000)
	.arcDashGap(() => getRandomInteger(3, 5))
	.arcDashInitialGap(() => getRandomFloat(1, 5))
	.arcDashLength(0.75)
	.arcStroke(1)
...
```

The above code works and shows data in the arc layer.

But, is there a bug when we add HTML elements?

Simply appending to the code above; I will see my HTML data layer but not the original arc data to go along with it:

``` typescript
Globe({ animateIn: false, waitForGlobeReady: true })
	.width(width)
	.backgroundColor("#FFFFFF00")
	.globeImageUrl("/assets/earth.jpg")
	.showAtmosphere(false)
	.onPolygonClick((polygon, ev, { lat, lng }) => polyClickHandler(polygon, lat, lng))
	.arcsData(<any>advisorFeatures)
	.arcColor("color")
	.arcDashAnimateTime(3000)
	.arcDashGap(() => getRandomInteger(3, 5))
	.arcDashInitialGap(() => getRandomFloat(1, 5))
	.arcDashLength(0.75)
	.arcStroke(1)
// adding new layer data below
	.htmlElementsData(<any>advisorFeatures)
	.htmlElement((d: any) => {
		const img = document.createElement("img");
		img.style.width = "50px";
		img.src = `/assets/${d.pinURL}`;

		return img;
	})
	.htmlAltitude(0.01)
	.htmlLat((d: any) => d.startLat)
	.htmlLng((d: any) => d.startLng)
```

Now I have a globe but WITHOUT the arcs.

BTW, thank you for this package.

**Comment by vasturiano** [comment]
@dunlavy thanks for reaching out.

The cause is that you're using the same data structure (`advisorFeatures`) for both layers. So the second layer wipes out the first. You should instead clone your data structure objects so that you're passing different ones for each layer. That should get them to work simultaneously.

**Comment by dunlavy** [comment]
Thank you.  I came back to the issue to comment that I can tell the arc data is there because of mouse hover:

![Layers](https://user-images.githubusercontent.com/6346817/222031050-2e6e91d5-172c-407d-a308-3fbe0505d293.png)

I will clone the data to see if the behavior changes.  At this point it appears to be a rendering issue.

Furthermore, reversing the order of the layers doesn't produce different behavior (i.e. the arcs override the appearance of the pins).  It seems HTML > arcs.

**Comment by dunlavy** [comment]
After updating the code:
`.htmlElementsData(<any>advisorFeatures)`

with:
`.htmlElementsData([...<any>advisorFeatures]) // clone array`

The issue still persists.  Thank you for the feedback on this issue!

**Comment by dunlavy** [comment]
I even tried slightly mutating the lat / lng in case duplicated points on the map cause for this behavior.  No luck with that either.

**Comment by dunlavy** [comment]
Update:  Going to try something.  I'll update issue with my findings.

**Comment by dunlavy** [comment]
You are correct.  My code did not adequately replace all the of the object references within the array.  After completely fetching two distinct sets of objects, it works beautifully.  Thanks again for this library.
