### ISSUE TITLE
[Feature request] Globe() manually release

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/globe.gl#15]
**Is your feature request related to a problem? Please describe.**
In many cases, we need to free all memory / three.js objects without refresh browser. e.g. one-page app or dev with hot-reload in webpack,...
But I can't find any way to release them in current version. Recall Globe() would create new scene but the old one seems remain in the memory, and the scene would be slow rendering.

**Describe the solution you'd like**
There could be an API, e.g myGlobe.destroy()/.free()/..., to release all canvas/dom/threejs objects in old scene.

**Comment by vasturiano** [comment]
@lslzl3000 for this purpose you can invoke the internal method `._destructor()` but it's merely a shortcut method that pauses the animation and empties all the layers, which you can do yourself directly.
https://github.com/vasturiano/globe.gl/blob/6dfbd2824e95dac2cb9af8664a8e37301871c381/src/globe.js#L231-L241

**Comment by lslzl3000** [comment]
@vasturiano Ok, that's a way to start. What about the canvas/doms and the Globe instance? I think we need to consider more to avoid memory leak

**Comment by vasturiano** [comment]
The three objects will be recycled as you empty the data layers. The DOM node is owned by the application so it's not up to the component to clean. The Globe instance will be garbage collected when unreferenced from your code.

**Comment by lslzl3000** [comment]
Thanks for reply, I will test _destructor() in my scenes. It seems work for me.

**Comment by chientrm** [comment]
`_destructor` work for me, too. Very nice!
