### ISSUE TITLE
Point of view jumping on click

### ISSUE THREAD

**Issue by jackkemmish** [vasturiano/globe.gl#151]
**Describe the bug**
I am using the `pointOfView()` function to rotate the globe on click which works as expected. The issue lies when clicking on a few different pins, with a slight delay before clicking on another pin, the globe spins out of control then goes to the selected pin.

**To Reproduce**
1. Have a few pins on the globe all with lat/lng values.
2. These pins are clickable, so when clicking use `world.pointOfView({ lat: d.lat, lng: d.lng, altitude: 1.4 }, 1000)` which will rotate the globe to the clicked pin.
3. Click a few different pins, then have a slight delay before clicking another one, the globe will spin uncontrollably before finsihing on the pin you just clicked.

**Expected behavior**
I'd assume the globe would just rotate naturally - but I do think there might be a potential build up as I have tried without a duration value and it just jumps, there's no uncontrolable rotation, however for the smooth effect I need the duration.

**Screenshots**
Below are some screenshots of the lat/lng I am logging to the console. The first 2 are as expected, then the 3rd one is much greater which results in the spinning before reaching the target pin.

<img width="176" alt="Screenshot 2023-04-11 at 15 47 53" src="https://user-images.githubusercontent.com/10498947/231201927-ecfbc2e2-df27-43f9-a4be-1004fa605ea8.png">
<img width="163" alt="Screenshot 2023-04-11 at 15 47 58" src="https://user-images.githubusercontent.com/10498947/231201936-3c919056-c928-4047-aa8f-e94b8b72b8b9.png">
<img width="145" alt="Screenshot 2023-04-11 at 15 48 10" src="https://user-images.githubusercontent.com/10498947/231201939-194f8c3a-9b69-4474-bd51-f64c2780ac8a.png">

Any help would be appreciated on this one!

Thanks,
Jack

**Comment by vasturiano** [comment]
@jackkemmish thanks for reaching out.

The easiest would be if you have a repro link with a simplified example, say at https://codepen.io/. This could be many things and it's difficult to say without looking more closely.
