### ISSUE TITLE
globeImageUrl 

### ISSUE THREAD

**Issue by SayedMajid** [vasturiano/globe.gl#152]
**Describe the bug**
When I pass the file path or the URL to the prop globeImageUrl, it doesn't show the globe. It only shows when I pass the unpkg URL which is commonly used in the codesandbox examples. I'm using Next.js, version 13

**Expected behaviour**
I just wanted to use my own full map Image and render/show it on the screen, unfortunately, it doesn't work other than the unpkg URL 

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Chrome
 - Version: 22

**Comment by vasturiano** [comment]
@SayedMajid this should work as long as you set the correct path for your file, and it's in a location that your web server can reach.

**Comment by SayedMajid** [comment]
Thanks, I tried a few images. It works for some URLs.
