### ISSUE TITLE
Pause all animation on arc hover with pauseAnimation?

### ISSUE THREAD

**Issue by triblondon** [vasturiano/globe.gl#153]
I'm not sure if this is a bug or if I'm just misinterpreting what this method does:

```js
  const g = Globe()(el)
    .onArcHover((a) => {
      g.controls().autoRotate = !a // works as expected :-)
      if (a) {
        g.pauseAnimation() // Doesn't do what I expected :-(
      } else {
        g.resumeAnimation()
      }
    })
```

This causes the globe to stop rotating when you hover an arc, but the arcs still animate (ie the line dash animation).  Ideally I'd like all motion to freeze, allowing the user to inspect the arc before it vanishes.

Is there a way to do that?

**Comment by vasturiano** [comment]
@triblondon thanks for reaching out.

I've just pushed an update that also freezes all the layer animations when you invoke `pauseAnimation`. Please upgrade to the latest published version.
