### ISSUE TITLE
Clouds layer makes globe itself disappear when spinning it

### ISSUE THREAD

**Issue by levelsio** [vasturiano/globe.gl#170]
**Describe the bug**
Cloud layer disappears along with the backgroundImage of globe when spinning it to the other side. This occurs on the Cloud demo on the site too at https://globe.gl/example/clouds/

**To Reproduce**
1. Go to https://globe.gl/example/clouds/
2. Drag globe to Asia
4. See it happen

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS Ventura 13.4
 - Browser: Chrome
 - Version: 115.0.5790.170

**Additional context**
Attached image dmeo
![CleanShot 2023-08-15 at 22 43 26](https://github.com/vasturiano/globe.gl/assets/7150848/b40f31d1-fd24-454d-aa05-7a02d6657e02)

**Comment by vasturiano** [comment]
Thanks for the heads up @levelsio. This is now fixed in the latest version of the module. Was an issue with the transparency between the various layers.
