### ISSUE TITLE
Starts a FrameTicker when imported

### ISSUE THREAD

**Issue by grassick** [vasturiano/globe.gl#171]
When importing the package globe.gl, it immediately starts a timer that can be seen in Chrome debugger, even without instatiating a globe. This is because of:

```
// Expose config from ThreeGlobe
var bindGlobe = linkKapsule('globe', ThreeGlobe);
```

**To Reproduce**

1. Import globe.gl into a esbuild project
2. Open Chrome debugger and run record in performance
3. See calls to frame-ticker

**Expected behavior**

It should not be running a ticker of any kind when the globe is not instantiated

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 115

**Comment by vasturiano** [comment]
Thanks for your report @grassick! I've just improved the cleanup mechanism, so you should no longer see any rafs from this module prior to instantiation. Please update to the latest version of the module.

**Comment by grassick** [comment]
I just installed it and confirmed that it works. Thank you for your quick fix and fabulous library! You can see the visualization I made with it at https://solstice.world
