### ISSUE TITLE
[Bug?] polygonCapCurvatureResolution won't update after creation

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/globe.gl#18]
**Describe the bug**
The new `polygonCapCurvatureResolution` method only apples in the first creation process. After that, the loop still running with new data or changes, but the polygon won't update. 

**To Reproduce**
1. Init polygons with `polygonCapCurvatureResolution(d=> d.active ? 1 : 10)`, it works fine
2. Change the active or reset polygonsData
3. the `polygonCapCurvatureResolution` loop will re-run, but the polygon won't change

**Expected behavior**
`polygonCapCurvatureResolution` will change the polygon layers after new loop

**Comment by lslzl3000** [comment]
By the way, as #17 suggestion, can we apply a filter for all accessor functions to reduce the loop? In most of cases, we only update one data at a time, so loop all of them is not a efficient way, especially related to geometry updating process

**Comment by vasturiano** [comment]
Thanks @lslzl3000. Should be fixed in `v2.12.2`.
