### ISSUE TITLE
make it easier to hit labels on mobile - e.g., transparent background for labels

### ISSUE THREAD

**Issue by black-snow** [vasturiano/globe.gl#185]
**Is your feature request related to a problem? Please describe.**
On mobile devices, I find it very hard to *touch* a label. You have to hit the letters exactly, which, suprisingly, ain't an easy feat to achieve. The spacing between the labels does not seem to be associated with the label.  
Actually, this is rather annoying on desktop systems as well - it's just way easier to hit the letters (or the dot) with a pointing device.

**Describe the solution you'd like**
I think it'd help a lot if there was a transparent layer behind the label's letters, that'd count as "hitting the label", too. Ideally with some padding around the text as well.

**Describe alternatives you've considered**
Hacking together an onclick on the globe itself, calculating the nearest data point and triggering its onclick event in case it's "close enough" to the data point.

**Additional context**
-

P.S.: At altitude above ~2.5 the points and labels flicker, both in my latest desktop FF and Chrome on mobile. Is there anything to do about this?
/edit: Setting a very low altitude seems to fix the flickering issue.

**Comment by carmoreira** [comment]
This would be an interesting feature to have, when using the labels with click events, it would help to have the hover/click event trigger also when the mouse/tap is between the letters of the label.

**Comment by vasturiano** [comment]
@black-snow thanks for reaching out and sorry for the wait here. 

I finally got around to adding an invisible object that follows the convex hull of the text object, so that it can be used for pointer trapping. If you upgrade to the latest version of the module (`2.33.1`), you shouldn't experience this nuisance anymore with pointer actions falling through the gaps of the text.

**Comment by black-snow** [comment]
That's awesome new! Thanks for your time @vasturiano

**Comment by carmoreira** [comment]
@vasturiano thank you for this! 
How easy would it be to access this invisible object and give it a colour?
