### ISSUE TITLE
Await for globe.labelDotRadius function

### ISSUE THREAD

**Issue by ElviraKukhtaruk** [vasturiano/globe.gl#187]
When i use **globe.labelDotRadius** function to change label dot radius:

```
globe.labelDotRadius(d => { 
    console.log('Before');
    return ...;
});

console.log('After');
...
```
I get the following output (Browser console):
```
> After 
> (5) Before 
```

I have some labelsData. I want to edit label dot radius (with **globe.labelDotRadius**), after that i need to preform some function after **globe.labelDotRadius** function is executed for **all elements**. Is it possible to achieve this behavior?

Thank you in advance.

**Comment by vasturiano** [comment]
@ElviraKukhtaruk the content of `labelDotRadius` will run asynchronously at the first available frame. So you just have to set your "after" code to be asynchronous too, using a `setTimeout`, for example.

In your example:
```js
globe.labelDotRadius(d => { 
    console.log('Before');
    return ...;
});

setTimeout(() => console.log('After'));
```

**Comment by ElviraKukhtaruk** [comment]
Thanks, that helps a lot.
