### ISSUE TITLE
pointsData([]) cannot clear points with pointsMerge(true)

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/globe.gl#19]
**Describe the bug**
With enable `pointsMerge`, the `pointsData([])` won't able to empty points

**To Reproduce**
1. add some points with `pointsData([...])`
2. also set `pointsMerge(true)`
3. try to empty points with `pointsData([])`
4. then you will see no points removed

**Expected behavior**
All points should be removed

I dont't test `hexBinMerge` yet, it may share the same problem

**Comment by vasturiano** [comment]
Thanks for reporting @lslzl3000.

There was a bug with the cleanup of the scene after updating when using merge geometries. And you're right that it was happening with the hexBin layer too.

Both issues are now fixed in `v2.12.3`. 👍
