### ISSUE TITLE
Ability to adjust the map on window resize event

### ISSUE THREAD

**Issue by WilliamSoler** [vasturiano/globe.gl#195]
Currently, if you try to resize the browser window after loading results on the following:

![image](https://github.com/vasturiano/globe.gl/assets/114860454/1a0a2278-e6ce-43f9-999e-72cb356c8dfb)

Empty spaces when increasing the window size. My attempt to auto-resize the globe to screen resulted in the following:

`
    window.addEventListener('resize', onWindowResize, false);

        function onWindowResize() {
           // Update camera aspect ratio and projection matrix
            camera = world.camera()
            renderer = world.renderer()
            controls = world.controls()

            camera.aspect = window.innerWidth / window.innerHeight;
            camera.updateProjectionMatrix();

            // // Update renderer size
            renderer.setSize(window.innerWidth, window.innerHeight);

        }
`
But results on an offset of the cursor with the globe:

![image](https://github.com/vasturiano/globe.gl/assets/114860454/3e5c4ce1-d073-452c-a99b-cd48b7909cf1)

Is there any way to achieve this resize without this cursor offset?

**Comment by vasturiano** [comment]
@WilliamSoler all you should need to do is invoke `.width(...)` and `.height(...)` directly on your globe component.
The rest is taken care of internally by the component.

**Comment by WilliamSoler** [comment]
@vasturiano Thank you it works 🙏🏼

**Comment by ralyodio** [comment]
this doesn't work for me using `.width('100vw');`
