### ISSUE TITLE
Update points dynamically

### ISSUE THREAD

**Issue by ArnaudBienner** [vasturiano/globe.gl#196]
Hi,

Using the points layer API, it would be great to be able to update the points once the globe has been rendered, to work with dynamic data.

Is this possible today?

Looking at the API documentation, I couldn't find a way to do this.

Did I miss something?

Maybe I can hack something by accessing objects through `.pointsData` and `__threeObj`, but having the possibility to this through the library would be better.

Another possibility would be to use the solution proposed in #161 (call `pointsData` with updated data), but it's not optimal because, for instance, the animation is not smooth if you want to reduce the size of a point or hide it.

**Comment by vasturiano** [comment]
@ArnaudBienner if you need to update the positions of the points, you just need to reinvoke the `.pointLat`, `.pointLng`, etc methods, to inform the module that it should recompute the positions.

**Comment by ArnaudBienner** [comment]
I'll try that.

Thanks a lot for your answer! (and for this great project :))
