### ISSUE TITLE
Attempted Import Error

### ISSUE THREAD

**Issue by ajmeese7** [vasturiano/globe.gl#197]
**Describe the bug**
I get the following error whenever I try to run my app:

```shell
Failed to compile.

./node_modules/globe.gl/dist/globe.gl.mjs
Attempted import error: 'Easing' is not exported from '@tweenjs/tween.js' (imported as 'TWEEN').
```

**To Reproduce**
1. `npm install --legacy-peer-deps`
2. `npm run start:dev` (maps to `env-cmd -e development node scripts/start.js`)
3. See error during compilation

**Expected behavior**
This same project was working before and it just recently stopped, I'm not sure why. I would imagine that a recent library update caused this change, but I haven't seen any applicable required migration guide.

**Desktop:**
 - OS: Zorin 17.1 Pro
 - Browser: Brave
 - Version: v1.64.113

**Additional context**
I have attached my [`package-lock.json`](https://github.com/vasturiano/globe.gl/files/14906046/package-lock.json) file for reference. I am currently using Node 16, but have encountered the same issue with Node 18.

**Comment by vasturiano** [comment]
@ajmeese7 I am unable to reproduce your import issue, even with the latest version of the module.

Could you see if you can make a simple reproducing example on https://codesandbox.io/ ?

You can also try resetting your `node_modules` folder, just in case it's some kind of local glitch that doesn't occur in other places.

**Comment by ajmeese7** [comment]
Nuking the `node_modules` didn't do anything, but deleting and reinstalling Node seemed to do the trick...

Guess it was just a ghost in the machine, my apologies!
