### ISSUE TITLE
resumeAnimation causes globe to spin very fast (catch up with missed autoRotation)

### ISSUE THREAD

**Issue by martenls** [vasturiano/globe.gl#199]
Im using the autoRotate feature of the globe controls and implemented a mechanism where the animation is paused when the page is not visible to save resources. 

```js
watch(pageVisibility, (current) => {
  if (current == 'visible') {
    if (gameState.value == GameState.PresetSelection && selectedPreset.value == Preset.World) {
      globe.controls().autoRotate = true;
    }
    globe.resumeAnimation()
  } else {
    globe.controls().autoRotate = false;
    globe.pauseAnimation()
  }
})
```
However, this causes the globe to spin very fast for a short amount of time after `resumeAnimation()` is called. It seems it tries to catch up to the rotation it would have usually reached in the time the tab was inactive (if the page is not active for a longer time the fast spin takes longer).

Is there any way to prevent this behavior?

**Comment by vasturiano** [comment]
@martenls thanks for your report.

I've just fixed this issue. IT was in another package that is a direct dependency of this one: [three-render-objects](https://github.com/vasturiano/three-render-objects). So all you should need to do is update your dependency tree to include at least `v1.29.4` of that package. Then you shouldn't experience this issue any more.

Please let me know if it fixes it for you.

**Comment by martenls** [comment]
I updated the dependencies and the issue is gone.

Thanks for the quick answer and for your work on the project!
