### ISSUE TITLE
Hex Bin Layer unable to access properties

### ISSUE THREAD

**Issue by idaflik** [vasturiano/globe.gl#206]
**Describe the bug**
the data below returns features with "geometry" and "properties". When creating a hex bin layer, globe.gl is able to access the coordinates but not the properties, it seems.

**To Reproduce**
Code:

`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Globe Visualization</title>
    <style>
        #tooltip {
            color: #364497;
            background-color: #f2f2f3;
            padding: 3px 5px;
        }
        #container {
            background-color: #f2f2f3;
        }
    </style>
    <script src="https://unpkg.com/d3"></script>
    <script src="https://unpkg.com/globe.gl"></script>
</head>
<body>
    <div id="container">
        <div id="globeViz"></div>
    </div>

    <script type="module">
        // Fetch the GeoJSON data and create buttons when the page loads
        fetch('https://raw.githubusercontent.com/idaflik/fics/main/output/hex_points_data.geojson')
        .then(res => res.json())
        .then(countries => {

            const dotScale = d3.scaleOrdinal()
                .range([0.1, 0.25, 0.4, 0.7])
                .domain(["yes", "uncertain", "replaced", "no"]);

            console.log(countries);
            
            // Create the globe visualization
            const world = Globe()
                .width(1000)
                .height(500)
                .backgroundColor("#f2f2f3")
                .showGlobe(false)
                .showGraticules(false)
                .showAtmosphere(false)
                .hexBinPointsData(countries.features)
                .hexBinPointLat(d => d.geometry.coordinates[1])
                .hexBinPointLng(d => d.geometry.coordinates[0])
                .hexTopColor(() => "#364497")
                .hexSideColor(() => "#36449700")
                .hexAltitude(0.005)
                .hexTransitionDuration(2000)
                // .hexMargin(() => 0.5)
                .hexMargin(d => dotScale(d.properties.WAPIS))
            (document.getElementById('globeViz'));
        })
        .catch(error => console.error('Error loading or processing GeoJSON data:', error));
    </script>
</body>
</html>`

returns "d.properties is undefined"

**Expected behavior**
The hexMargin to change based on the values of WAPIS property.

**Additional context**
Hope this makes sense and I didn't overlook anything obvious

**Comment by vasturiano** [comment]
@idaflik as described in the docs, the signature of the `hexMargin` accessor function is as follows:
```js
hexMargin(({ points, sumWeight, center: { lat, lng }}) => ...)
```

This is necessary because a single hex bin can represent many different points, so those are included as an array in the passed parameters.

**Comment by idaflik** [comment]
thank you!
