### ISSUE TITLE
.heatmapColorFn() doesn't accept custom color functions

### ISSUE THREAD

**Issue by idaflik** [vasturiano/globe.gl#215]
**Describe the bug**
I am having issues changing the color scale of the heatmap layer. In the docs it says 

> Heatmap object accessor function or attribute for the color interpolator function to represent density in the heatmap. This function should receive a number between 0 and 1 (or potentially higher if saturation > 1), and return a color string.

I write a function that takes values from 0 to 1, set saturation to 1 but keep getting the error `Uncaught TypeError: d is not a function`. Please see the example below

**To Reproduce**

```
 <script src="https://colorjs.io/dist/color.global.js"></script>
  <script>
    function componentToHex(c) {
      var hex = c.toString(16);
      return hex.length == 1 ? "0" + hex : hex;
    }

    function rgbToHex(r, g, b) {
      return "#" + componentToHex(r) + componentToHex(g) + componentToHex(b);
    }

    let c1 = new Color("rebeccapurple");
    let c2 = new Color("lch", [85, 100, 85]);
    let interpolator = c1.range(c2, { space: "lch", outputSpace: "xyz" });

    const interpolHex = function (value) {
      return rgbToHex(
        Math.floor(interpolator(value).coords[0] * 255),
        Math.floor(interpolator(value).coords[1] * 255),
        Math.floor(interpolator(value).coords[2] * 255)
      );
    };

    console.log(interpolHex(1));
    console.log(interpolHex(0));

    fetch(
      "https://raw.githubusercontent.com/vasturiano/globe.gl/master/example/datasets/world_population.csv"
    )
      .then((res) => res.text())
      .then((csv) =>
        d3.csvParse(csv, ({ lat, lng, pop }) => ({
          lat: +lat,
          lng: +lng,
          pop: +pop,
        }))
      )
      .then((data) => {
        const globeViz = document.getElementById("globeViz");
        const globe = Globe()(globeViz)
          .heatmapsData([data])
          .heatmapPointLat("lat")
          .heatmapPointLng("lng")
          .heatmapPointWeight("pop")
          .heatmapBandwidth(0.9)
          .heatmapColorSaturation(2.8)
          .heatmapPointWeight((d) => d.pop * 5e-5)
          .heatmapTopAltitude(0.2)
          .heatmapColorFn((d) => interpolHex(d))
          .heatmapColorSaturation(1)
          .enablePointerInteraction(false);

        // Function to adjust the size of the globe canvas to fit the container
        function resizeGlobe() {
          const width = globeViz.clientWidth;
          const height = globeViz.clientHeight;
          globe.width(width).height(height); // Update the globe size
        }

        // Call this function once to set the initial size
        resizeGlobe();

        // Add an event listener to resize the globe whenever the window is resized
        window.addEventListener("resize", resizeGlobe);

        // });
      });
  </script>
```

I have tried the variations
` .heatmapColorFn(() => interpolHex())`
` .heatmapColorFn((d) => interpolHex(d.pop))`
 `.heatmapColorFn(interpolHex())`
 `.heatmapColorFn(interpolHex)`
`.heatmapColorFn("interpolHex")`
`.heatmapColorFn([interpolHex])`
`.heatmapColorFn([interpolHex()])`
`.heatmapColorFn([(d) => interpolHex(d)])`
`.heatmapColorFn([(d) => interpolHex(d.pop)])`

none of which worked.

if I comment out the line with heatmapColorFn, it works.

**Expected behavior**

The same result as when the heatmapColorFn line is commented out, but with a gradient between yellow and purple as specified in the interpolHex function.

Please, any help greatly appreciated.
Best!

**Comment by vasturiano** [comment]
@idaflik the correct format should be:
```js
.heatmapColorFn(() => interpolHex)
```

which is a shortcut for a function within a function:

```js
.heatmapColorFn(() => d => interpolHex(d))
```

Why, because this is a heatmap object accessor function, so the outer function receives a heatmap object. This is necessary in case there's more than one heatmap in this layer. Hope that makes sense.

**Comment by idaflik** [comment]
Oh amazing, thank you so much!
