### ISSUE TITLE
Arcs incorrectly positioned and other layers stop responding after conditional value updates

### ISSUE THREAD

**Issue by PButcher** [vasturiano/globe.gl#218]
**Describe the bug**
- I want to increase the altitude of points based on an active ID which I increment every _x_ seconds.
- All other points should have a lower altitude, essentially highlighting the active point.
- I also want an arcs layer to show the links between points, at all times.

As an example, if I change `pointsAltitude` and/or `pointsColor` based on whether my active ID variable matches the ID in the data, the color and altitude do not update, and the arcs layer glitches out.

I have created a minimal example on CodeSandbox with Globe.gl (see below) for you to take a look at.

I have created implementations in `globe.gl`, `react-globe.gl` and `three-globe` and the same bug occurs in each implementation.

**To Reproduce**
1. Go to [https://codesandbox.io/p/sandbox/8wzy3j](https://codesandbox.io/p/sandbox/8wzy3j)
2. Wait 5 seconds for the first interval tick
3. You will notice the arc lines change (elongate outwards) and `pointAltitude` and `pointColor` do not update after the first tick.
4. Comment out lines 53 and 56 where I change `globe.pointColor` and `globe.pointAltitude`.
5. You will notice the arcs are fine, and the pov changes.

**Expected behavior**
I expect to be able to conditionally change properties on a single data point without affecting other layers. For example, if you comment out line 28 (`.arcsData([...data])`) of [https://codesandbox.io/p/sandbox/8wzy3j](https://codesandbox.io/p/sandbox/8wzy3j), the point altitudes update as expected.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1 (23C71)
 - Browser: Chrome 128.0.6613.138 (Official Build) (arm64)
 
 Thanks for your excellent component, and I hope that there is a simple workaround or fix for this.

**Comment by vasturiano** [comment]
@PButcher thanks for reaching out.

The main issue here is that you're sharing data objects between layers so they start conflicting. You should only associate a single data element to one layer. I see that when you're invoking `pointsData` and `arcsData` you're spreading the arrays, but that only clones the array object itself, the data elements remain the same.

I've done a small alteration to your code that clones the elements themselves, you can see it working here:
https://codesandbox.io/p/sandbox/globe-gl-data-issue-repro-forked-67qfcw

**Comment by PButcher** [comment]
@vasturiano thanks for the speedy reply. That makes a lot of sense, thanks for providing an example also!
