### ISSUE TITLE
Doesn't support Safari on iOS...

### ISSUE THREAD

**Issue by IamMilev** [vasturiano/globe.gl#23]
When opened in Safari browser, either on desktop or mobile, it doesn't work. Just loads up to black screen.

**To Reproduce**
1. Go to the Arcs example ( https://globe.gl/example/airline-routes/us-international-outbound.html ) in Safari

**Expected behavior**
Expecting to see the globe and to interact with it.

**Desktop (please complete the following information):**
 - iOS
 - Safari
 - Version in iOS 14

**Smartphone (please complete the following information):**
 - iPhone 7, iMac 27" 2019
 - iOS 14, macOS Catalina
 - Safari

**Additional context**
It happens only on Safari, and only with the Arcs example. The other browsers are okay.

**Comment by rberenguel** [comment]
On iPad (Mini 5th gen, iOS 14) it briefly appears, then the page turns blank. But if you drag or pinch it appears again. The example in the library works on the first open though (https://vasturiano.github.io/three-globe/example/links/)

**Comment by AlexGustafsson** [comment]
For me all examples work on Safari on iOS 14.2 and macOS 11.0.1. The example you're referring to loads in quite a lot of data and as such the performance isn't that great. That's likely not the fault of this package, however.

**Comment by rberenguel** [comment]
Indeed, the blank page was me being impatient. Once cached it works just fine.
