### ISSUE TITLE
.2 precision in globe.js

### ISSUE THREAD

**Issue by ryan-veracitek** [vasturiano/globe.gl#30]
Have had to patch this static value to .05 to get accurate behavior. Is there a consequence? Would you consider .05 as the default?

Thank you.

**Comment by vasturiano** [comment]
@ryan-veracitek are you referring to the `lineHoverPrecision`? This would affect only the interaction precision of the arcs and paths layers, when in `Line` mode (`undefined`  stroke).

The set value was picked as it works relatively well in most circumstances. Could you describe the problem you're trying to solve by modifying it? If justified we could potentially make it customizable.

**Comment by ryan-veracitek** [comment]
Sure, and thanks for your response. We overlay polygons, with it at .2 we see it return the wrong object onHover. It will often return an adjacent object. With it at .05 we get much better accuracy on detecting which polygon is being hovered over. It's ok if you don't want to change the codebase, we're patching fine, but it's a tricky one if someone stumbles on it.

**Comment by vasturiano** [comment]
@ryan-veracitek my understanding is that this precision only affected the raycaster precision of line objects, so polygons or any other 2+ dimensional objects should not be affected by it.

It's being applied here: https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.js#L245

And according to threejs docs on the line threshold param: https://threejs.org/docs/#api/en/core/Raycaster.params

Are you sure you're observing a difference in the polygon hover when modifying this value?

**Comment by ryan-veracitek** [comment]
Yessir, absolutely when I patch that single value .2 into .05 rather than return the adjacent polygon (in certain rare cases) the hover returns the correct one. The effect can be seen somewhat readily among adjacent polygons if you set that number from .2 to 1 and then show the tooltip on hover with unique identifiers among the polygons. Call one A & another B... you'll find you can move well beyond the border of B before the callback changes the tooltip to A. The higher that number the worse the effect.

Perhaps it's using those lines for border/boundary detection and the higher precision value causes that border to appear much wider to the algorithm? .2 worked in most cases, even with much smaller polygons but it seems that if a small polygon is positioned in just the right spot between two others it would effectively disappear to the hover.

Thank you again for your response.

**Comment by ryan-veracitek** [comment]
I checked your COVID map and you're not showing an Andorra polygon. I suspect if you had polygon hovers and showed Andorra you'd see the mouse hover not work correctly at .2 and work correctly at .05.

**Comment by vasturiano** [comment]
@ryan-veracitek sorry for the hold on this case.

The mystery is finally revealed. The part of the polygon object that was being affected by the line hover precision is the polygon stroke. That contour line surrounding the shape, and activated by `polygonStrokeColor `, is a `Line` object and that's what was introducing the artifact related to the hover margin.

To address this, I've exposed the `lineHoverPrecision` method. Its default value remains the same at `0.2`, but it can be modified to other values (including `0`, if no hover margin is desired) like so:
```js
myGlobe.lineHoverPrecision(0.01)
```

Hopefully this fixes your case.

**Comment by ryan-veracitek** [comment]
No problem at all this really should cover it! Thanks.
