### ISSUE TITLE
Arc lines become hard to see and at times invisible when on light backgrounds.

### ISSUE THREAD

**Issue by DanMattina** [vasturiano/globe.gl#35]
On light backgrounds or light globe color, the arcs lines become hard to see or even invisible at times

1. Create a globe and set the globe to .backgroundColor('white')
2. Turning on any arcs, you can see what I'm seeing below
 
![Screen Shot 2021-03-03 at 8 33 11 AM](https://user-images.githubusercontent.com/19392290/109815194-5ea8df80-7bfd-11eb-8cac-83923676ded4.png)

Is there any way to change arc opacity or even blending mode so that these arcs are visible? Is this an issue with the light backgrounds and if so is there a workaround for this to work on light backgrounds. 

 - OS: Mac and PC
 - Browser Tested in Safari, Chrome and Firefox

**Comment by vasturiano** [comment]
@DanMattina thanks for reaching out.

The line blending mode was set to additive which is more suitable for dark backgrounds but doesn't work very well on light backgrounds. I've switched it to normal blending which works fine in both. Please try it with the latest published version (`2.18.1`).

**Comment by DanMattina** [comment]
That worked great!
