### ISSUE TITLE
Map images and Zoom trigger?

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/globe.gl#4]
Is there any good place to get images to use for this globe? Or do you have any specifications on sizes it should use?

I have been looking for awhile and can't find a spot to get images i can use for wrapping around the globe.

Also is there any access to a zoom triggered function? I would like to try loading a more detailed map when zoomed in to a certain level, also maybe load different set of data at that point? So points can be clustered together when zoomed out and expand when zoomed in enough.

**Comment by vasturiano** [comment]
@Alexithemia you can find a nice collection of globe images from NASA's blue marble set: https://visibleearth.nasa.gov/collection/1484/blue-marble

As for the zoom events, I've just added a new method `onZoom` which lets you add your handler callback:
```
onZoom(({ lat, lng, altitude }) => /* your code /*)
```

**Comment by kkhanhluu** [comment]
Can I prevent user from zooming when he scrolls the mouse?

**Comment by vasturiano** [comment]
@kkhanhluu you can disable zooming abilities from the [orbit controls](https://threejs.org/docs/#examples/en/controls/OrbitControls).
```
myGlobe.controls().enableZoom = false
```

**Comment by iamanas20** [comment]
Hey @vasturiano, How can I programmatically zoom in and out, using + and - button for example?

**Comment by TomSB1423** [comment]
> Thanks a bunch!

Did you manage to load more detailed maps on zoom? I am thinking of doing a similar thing, any guidance would be appreciated.

**Comment by j2is** [comment]
Hey @Alexithemia and @TomSB1423 did you manage to load more detailed maps on zoom?
