### ISSUE TITLE
[question]How do I write code to stop/resume autoRotate when mouse click?

### ISSUE THREAD

**Issue by maker2002** [vasturiano/globe.gl#49]
I just find a example here:
https://github.com/vasturiano/react-globe.gl/issues/55#issuecomment-847450561
But it doesn't work in this version.

1.How do I write code to stop/resume autoRotate when mouse click?
2.Which version should I use? Ract ver or this ver? for performance wise?

Thanks for the great work!

**Comment by vasturiano** [comment]
1. You can set auto-rotation of the globe via:
```js
myGlobe.controls().autoRotate = false; // or true
```
So you just need to associate that action to your click event.

Additionally, if you just want to cancel the auto-rotation when the user manually zooms/pans the globe, you can do this:
```js
// assuming auto-rotation has been previously engaged
const controls = myGlobe.controls();
controls.addEventListener('start', () => controls.autoRotate = false);
```

2. Performance wise, both versions should be equivalent. You can choose whichever framework is more convenient for your app.

**Comment by maker2002** [comment]
Thank You!
