### ISSUE TITLE
react compatibility?

### ISSUE THREAD

**Issue by edwmurph** [vasturiano/globe.gl#5]
**Is your feature request related to a problem? Please describe.**
is this library easily integratable into a react project?

**Describe the solution you'd like**
might be nice for the readme to be updated to have a react quickstart guide

**Describe alternatives you've considered**
you could just explain it to me in this issue thread

**Additional context**

**Comment by vasturiano** [comment]
@edwmurph actually the readme does reference a React binding: https://github.com/vasturiano/react-globe.gl
😃
