### ISSUE TITLE
No support for unicode in text labels

### ISSUE THREAD

**Issue by snshn** [vasturiano/globe.gl#56]
**Describe the bug**
Unicode within label text gets rendered as `???`.

**To Reproduce**
1. Go to https://jsfiddle.net/k37vqzab/

**Expected behavior**
Expected unicode symbols to be properly rendered.

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
—

**Comment by snshn** [comment]
Potentially the font that's baked into the component is limited, hence using `labelTypeFace` and http://gero3.github.io/facetype.js/ as described in README.md is the way to go.  Perhaps specifying the range of supported characters next to `labelTypeFace` could serve as a heads up that unicode symbols are not being rendered by default.

**Comment by vasturiano** [comment]
@snshn yes, the font type should be the reason for that. See another example of this at: https://github.com/vasturiano/react-globe.gl/issues/50
