### ISSUE TITLE
How to display country names in Polygons？

### ISSUE THREAD

**Issue by jinzhe** [vasturiano/globe.gl#57]
I want to display the country name in the polygon, but the api does not seem to have a relevant method.

**Comment by vasturiano** [comment]
@jinzhe you have `polygonLabel` if you'd like to display any content in the tooltip on polygon hover. If you'd like to add permanently visible labels you can use the [labels layer](https://github.com/vasturiano/globe.gl#labels-layer) to add a label to each polygon, potentially at the centroid of each polygon.

**Comment by jinzhe** [comment]
After using label, it can be displayed, but Chinese cannot be displayed. Can you tell me how to use labelTypeface?

Such as using this

https://www.wjceo.com/lib/fonts/MicrosoftYaHei_Regular.json

```js
import facetype from "./facetype";
...
       world.labelText('label')
       .labelSize(1.2)
       .labelDotRadius(0.4)
       .labelAltitude(0.01)
       .labelDotOrientation(d =>'top')
       .labelColor(d => "#FDCA69")
       .labelTypeFace(facetype)
```
But running error!

![WechatIMG35](https://user-images.githubusercontent.com/4435082/124340918-597b9180-dbeb-11eb-8198-beba3cbca5ac.png)

**Comment by vasturiano** [comment]
@jinzhe does this help? https://github.com/vasturiano/globe.gl/issues/26

**Comment by jinzhe** [comment]
Thank you, it has been resolved!
