### ISSUE TITLE
Mobile version scroll vs rotate gestures

### ISSUE THREAD

**Issue by dlauc** [vasturiano/globe.gl#58]
Thank you for the great component. My issue is that when the globe is in the middle of a mobile page, it clashes with the webpage scroll (the globe rotate and it is hard or impossible to scroll down the page). I know this is not a specific problem but it would be great if there is a workaround for the recognition of different gestures (scroll vs rotate).

**Comment by vasturiano** [comment]
@dlauc thanks for reaching out.

You can access the [Orbit controls configuration](https://threejs.org/docs/#examples/en/controls/OrbitControls) via `myGlobe.controls()`. From there you can setup what's more suitable for you app, for example by disabling the rotation ([myGlobe.controls().enableRotate = false](https://threejs.org/docs/#examples/en/controls/OrbitControls.enableRotate)) when the page is scrolling.

**Comment by dlauc** [comment]
thanks
