### ISSUE TITLE
How to add real-time data?

### ISSUE THREAD

**Issue by vikgmdev** [vasturiano/globe.gl#6]
There's any way of how to add `arcsData` in real-time, my plan is to get a socket connection receiving lat and long with source and destination and go adding this data to the current globe as they arrive but I'm not sure if that possible with the current implementation.

I'm also trying also to set a world map in png with transparency for the ocean using the `globeImageUrl` but it set white for the whole ocean, any idea about this?

PS: Thanks a lot to create this library!

**Comment by vasturiano** [comment]
@vikgmdev you can just re-call `arcsData` with the updated list of links whenever you wish to add/remove arcs.

As for the `globeImageUrl` I'm not sure. Could you make an example, on https://codesandbox.io/ or so, to debug further?

**Comment by vikgmdev** [comment]
@vasturiano I tried that but it didn't work as I expected, I think what I need is something more custom, so I'm trying to add a custom layer instead based on the `Arcs` one.

Do you have any steps to setup `three-globe` and `globe.gl` for development?

**Comment by vasturiano** [comment]
@vikgmdev for local dev, the easiest setup is to run `yarn dev` and point the script tag on your html to your local bundle, for example:
```
<script src="./dist/globe.gl.js"></script>
```

If you want to develop both modules in tandem, you can use [package symlinking](https://yarnpkg.com/lang/en/docs/cli/link/).
