### ISSUE TITLE
Can not display Chinese characters?

### ISSUE THREAD

**Issue by 350050183** [vasturiano/globe.gl#62]
**Describe the bug**
Can not display Chinese characters?

**Screenshots**
![image](https://user-images.githubusercontent.com/12798824/128487071-45efbbc4-8908-4d11-bea4-977703bc42cb.png)

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 5.0+
 - Browser: Tencent Browser
 - Version: latest

**Additional context**

**Comment by vasturiano** [comment]
Please see https://github.com/vasturiano/globe.gl/issues/26
