### ISSUE TITLE
Directional Light Helper not showing up.

### ISSUE THREAD

**Issue by franciscosierra1915** [vasturiano/globe.gl#63]
Hello, 

I'd like to see the position of the directional light in my scene, but I can't make it show up. This is my code:
```
<script>

    const world = Globe()
      .globeImageUrl('./earth.jpg')
      .bumpImageUrl('./earth_bump.png')
      .pointOfView({lat:35.44,lng:-99.21,altitude:1.5}, 1000)
      (document.getElementById('globeViz'));

    const globeMaterial = world.globeMaterial();
    globeMaterial.bumpScale = 5;
    new THREE.TextureLoader().load('./earth_specular.jpg', texture => {
      globeMaterial.specularMap = texture;
      globeMaterial.specular = new THREE.Color('#ccc');
      globeMaterial.shininess = 25;
    });

    setTimeout(() => {
      const scene = world.scene();
      const directionalLight = scene.children.find(obj3d => obj3d.type === 'DirectionalLight');
      const helper = new THREE.DirectionalLightHelper(directionalLight, 100);
      scene.add(helper);
    
    }, 2000);
  </script>
```

**Comment by vasturiano** [comment]
@franciscosierra1915 thanks for reaching out.

I've just plugged a helper like yours into the [custom globe styling example](https://globe.gl/example/custom-globe-styling/), and it worked:
<img width="762" alt="Screenshot 2021-09-06 at 20 51 30" src="https://user-images.githubusercontent.com/6784226/132257098-97867f07-c975-4d3e-9a0f-0ffbc2848240.png">

Have you not managed to get it to work?

**Comment by franciscosierra1915** [comment]
I got it working! Thanks so much for your help!
