### ISSUE TITLE
[Question] Best way way to automatically rotate the globe

### ISSUE THREAD

**Issue by ian-whitestone** [vasturiano/globe.gl#73]
I'm curious about the best way to automatically rotate the globe, in order to achieve a similar effect to the [Github globe](https://github.com/home).

Right now I have this code, which appears to be doing the trick.

```javascript
function animate() {
    let pov = globe.pointOfView();
    pov['lng'] -= 0.05
    globe.pointOfView(pov)
};
animate()
```

But I'm wondering if this is the best approach? Another option would be modifying the underlying [three-globe object's rotation](https://github.com/vasturiano/three-globe/blob/9c49999a030c9f34c21a5d8c712366af84919197/src/layers/globe.js#L59-L61) (i.e. `globeObj.rotation.y += desiredRotationAmount`), but I couldn't find a way to access that object with `globe.gl` (I'm a JS noob, so maybe there is a way?)).

Any advice would be greatly appreciated!

Note, if you'd prefer me to ask questions elsewhere, like stackoverflow, lemme know and I will happily move!

**Comment by vasturiano** [comment]
@ian-whitestone while those approaches would work, I think the simplest way is to set auto-rotate on the [Three orbit controls](https://threejs.org/docs/#examples/en/controls/OrbitControls.autoRotate), as in this example:
https://github.com/vasturiano/globe.gl/blob/e7bfcc1408b97713d263838b6e8895d0514f64b5/example/countries-population/index.html#L23-L25

**Comment by ian-whitestone** [comment]
Thanks @vasturiano, apologies for not searching more thoroughly.
