### ISSUE TITLE
add moving clouds feature

### ISSUE THREAD

**Issue by rivebe** [vasturiano/globe.gl#74]
Hi @vasturiano, first off. Thank you for this amazing wrapper/work! One feature request would be to make it easy to add in moving clouds, which rotate arround the globe.

An example as seen and explained here:
http://thematicmapping.org/playground/webgl/earth/
See bottom of the article: https://blog.mastermaps.com/2013/09/creating-webgl-earth-with-threejs.html?m=1

I've tried adding non-moving clouds with the current functionality available:
const globeMaterial2 = world.globeMaterial();
    new THREE.TextureLoader().load('clouds/earthcloudmaptrans.jpg', texture2 => {
	texture2.side     = THREE.DoubleSide;
	texture2.opacity     = 0.8;
	texture2.transparent = true;
	texture2.depthWrite  = false;
	globeMaterial2.alphaMap = texture2;

But I fail achieving the correct visualisation. Am I chossing the wrong material map?

**Comment by vasturiano** [comment]
@rivebe thanks for reaching out. 

I've just added [an example](https://globe.gl/example/clouds/) that includes moving clouds. You can check out the example source code here: https://github.com/vasturiano/globe.gl/blob/master/example/clouds/index.html
