### ISSUE TITLE
Responsive view

### ISSUE THREAD

**Issue by sorxrob** [vasturiano/globe.gl#8]
Is there an easy way to make the container responsive? Currently when you resize the window, the globe stays in its place.

Any help would be much appreciated.

**Comment by sorxrob** [comment]
This is the website btw https://covid-3d.now.sh

**Comment by vasturiano** [comment]
@sorxrob nice implementation! I've made a similar one at https://observablehq.com/@vasturiano/corona-virus-covid-19-globe

Regarding making it responsive, you can do that by manipulating the `width` and `height` properties. And if you prefer you can use something like [element-resize-detector](https://github.com/wnr/element-resize-detector) to detect changes to your window size.

**Comment by sorxrob** [comment]
> @sorxrob nice implementation! I've made a similar one at https://observablehq.com/@vasturiano/corona-virus-covid-19-globe
> 
> Regarding making it responsive, you can do that by manipulating the `width` and `height` properties. And if you prefer you can use something like [element-resize-detector](https://github.com/wnr/element-resize-detector) to detect changes to your window size.

Nice! Thanks for the API. I'm still checking how to set the width/height dynamically in your docs. Thanks!

**Comment by sorxrob** [comment]
Adding this made it responsive. Thank you.

```
window.addEventListener('resize', (event) => {
  world.width([event.target.innerWidth])
  world.height([event.target.innerHeight])
});
```

**Comment by wobsoriano** [comment]
Hi @vasturiano , looking at the population number, using this formula

`d3.format('.3s')(d.POP_EST)`

Millions become `M` and Billions become `G`. Is that `G` another term for billion? Thanks.

**Comment by snshn** [comment]
Ah, perfect, thank you so much @wobsoriano!

**Comment by kqwq** [comment]
thanks so much @wobsoriano

**Comment by chavinlo** [comment]
Thanks @wobsoriano

**Comment by ralyodio** [comment]
i get a flash of white when i resize. how do i fix this?

**Comment by ben221199** [comment]
@ralyodio If your background canvas is mainly black (for example, if you use `night-sky.png`), then make your <body> background also black, using the CSS rule `background:black;`.
